# frozen_string_literal: true
source 'https://supermarket.chef.io'

cookbook 'mongo-server', git: 'https://github.com/maigbodi/Mongodb_cookbookEng2932.git'

cookbook 'node', git: 'https://github.com/maigbodi/node_cookbook_eng17.git'

metadata
